<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sushils-MacBook-Air.local" failures="1" tests="7" name="com.test.parabank.TestAdminPage" time="19.873" errors="0" timestamp="2020-02-05T23:42:31 IST" skipped="0">
  <testcase classname="com.test.parabank.TestAdminPage" name="triggerBrowser" time="1.266"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="testAccessMode" time="1.202"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="adminTest" time="6.251"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="applicationSettings" time="0.463"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="testWebService" time="2.196"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="testApplicationSettings" time="8.322"/>
  <system-out/>
  <testcase classname="com.test.parabank.TestAdminPage" name="failTheTest" time="0.173">
    <failure message="expected [-1] but found [1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.test.parabank.TestAdminPage.failTheTest(TestAdminPage.java:137)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- failTheTest -->
  <system-out/>
</testsuite> <!-- com.test.parabank.TestAdminPage -->
